### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minamotoryuu** [minamotoryuu/Ghost#1]
server.py
- [ ] human-readable addresses(e.g. e-mails) support
- [ ] online status checking support
- [ ] own server creation support
